### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by Zeshengx**
Improve waypoint function, using long press to add waypoint.
Update the latest version core.jar.

### CODE REVIEW

**Comment by psigen** [comment]
Thanks for fixing the namespacing!
Is this version working for @shantanu-vyas and @christomaszewski?

**Comment by shantanu-vyas** [comment]
I'm seeing a couple things but nothing crucial and I'll have them fixed in the merge where I add the waypoint save and load ability. 
- Connecting over wifi (using the tablet as both the server and client) causes a crash.
- Delete All Waypoints sometimes crashes.
- Delete All Waypoints removes boat marker sometimes?.Looking into this one.

**Comment by Zeshengx** [comment]
@shantanu-vyas  I thought I fixed the third bug. The boat is represented by a green arrow and it won't delete with other waypoints.

**Comment by Zeshengx** [comment]
@shantanu-vyas  How do you test the app to see the third bug? May be I didn't do the same test and thought I fixed the bug.

**Comment by shantanu-vyas** [comment]
I think the issue was before you actually connect the app places a marker at panther hollow and that was the one getting removed with Delete All Waypoints. Everything looks good otherwise.

**Pull request merged**
